baseURL = "https://satoshicano.dev/"
defaultContentLanguage = "ja"
title = "satoshicano's Blog"

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[params]
  env = "production"
  description = "Software engineer working in Japan."
  keywords = ["Blog", "Engineering", "Hugo"]
  author = "satoshicano"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  UseHugoToc = true
  disableSpecial1stPost = true
  disableScrollToTop = false
  comments = false
  math = true

  [params.assets]
    favicon = "favicon.ico"
    favicon16x16 = "favicon.ico"
    favicon32x32 = "favicon.ico"
    apple_touch_icon = "favicon.ico"

  [params.label]
    text = "satoshicano's Blog"

  [params.homeInfoParams]
    Title = "Hi, I'm satoshicano."
    Content = "Software engineer working in Japan."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/satoshicano"

  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/satoshicano"

  [[params.socialIcons]]
    name = "instagram"
    url = "https://instagram.com/satoshicano"

[markup]
  [markup.highlight]
    noClasses = false
